### PR TITLE
Feature/args id pass (For #4)

### PR DESCRIPTION
**Pull request by greymd**
New features
* `-i` and `--id` options.
  + User can specify temporal `TTCP_ID`.
* `-p` and `--password` options.
  + User can specify temporal `TTCP_PASSWORD`.

If this PR is merged, I suppose, the version will be `v1.1.0`.
How about following Semantic Versioning (http://semver.org/lang/ja/) ?
The rule like this.

* Major version up -- New features with NOT keeping backward compatibility.
* Minor version up -- New features with keeping backward compatibility.
* Patch version up -- Bug fix with keeping backward compatibility.

### CODE REVIEW

**Review by mecab — CHANGES_REQUESTED** [review]
Good job👍

Two points:
 1. The message such as "Set environment variable (TTCP_ID)." is now not appropriate . Consider add the words like "or give the ID by -i"

 2. I found the app get stuck if we pass the option which is not registered (e.g., -z). It should be fixed. Perhaps it should be fixed as the other issue as it is potential bug in the parser.

**Comment by mecab** [comment]
Reviewed📝. And I agree for the versioning!

**Comment by greymd** [comment]
@mecab Fixed!
As for the exit status, let's discuss other issues..

いやー、終了ステータスの決め方わからんｗ
別で決めましょう。。

**Review by mecab — APPROVED** [review]

**Comment by mecab** [comment]
[LGTM](https://lgtm.in/i/4wNcY8yTp)

**Comment by mecab** [comment]
確かに不正終了のパターン増えてきたしそろそろ終了コードちゃんと考えないとですねｗ  #25 見ておきます。

**Pull request merged**
