### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by mecab**
I beg your kindness to put my name on it with the first release... 😳😳😳

### CODE REVIEW

**Comment by greymd** [comment]
@mecab Ohhhhhhh, sorry I forgot it!!

**Comment by mecab** [comment]
💕 🙇  💕

**Comment by greymd** [comment]
Why CI fails 😭

**Comment by mecab** [comment]
😢

**Comment by greymd** [comment]
If cl1p.net fails, tests also fails. Tests are depending on the external services :(

**Comment by greymd** [comment]
I am lazy. merge 😆

**Comment by mecab** [comment]
:rofl:

**Pull request merged**
