### PR TITLE
Feature/proxy

### PR DESCRIPTION
**Pull request by greymd**
New features for #27 

* Support `TTCP_PROXY` variable.
* CI uses docker to simulate proxy server.
  + New `Dockerfile` is added for test.
  + https://hub.docker.com/r/greymd/ttcopy-test-proxy/~/settings/collaborators/
* Update `README.md`
* Refactoring `test.sh`
  + I believe results became more readable one.

After this merge, I think the version will be `v2.2.0`.

### CODE REVIEW

**Review by mecab — COMMENTED** [review]
Nice work. You are the hero of the people in the firewall 😆 
It seems to be good!

How about using existing squid repository instead of providing custom one so we can keep the repo simple.
(such as https://hub.docker.com/r/sameersbn/squid/ (more stars) or https://hub.docker.com/r/minimum2scp/squid/ (more pulls) )
It's up to you, though. Anyway nice idea to use docker to test proxy ⭐️ .

**Comment by greymd** [comment]
@mecab Thank you for you feedbacks!!
ok, I will work on it. (Update  will probably be late cuz I would be busy this several days..)

**Comment by mecab** [comment]
@greymd Ok, I fixed it using `sameersbn/squid` and pushed to `feature/proxy-no-dockerfile`.  If you agree, I'll merge it into this PR then will merge into master.

**Comment by mecab** [comment]
By the way, the version will be `2.1.0`, not `2.2.0` ?

**Comment by greymd** [comment]
oh, that's true. next should be `2.1.0`.

**Comment by greymd** [comment]
@mecab Hi, I've checked `feature/proxy-no-dockerfile`. Good job 💯 
`docker pull` is not necessary indeed.

> If you agree, I'll merge it into this PR then will merge into master.

✔️  Approve

**Comment by mecab** [comment]
Merged!

**Pull request merged**
