### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by greymd**
yeeeeeeeaaaaaaaaaah!!!!
Prime number version!!!!!

### CODE REVIEW

**Comment by mecab** [comment]
#27 ?

**Comment by greymd** [comment]
Sorry for confusing you...

The reason why I made `develop-2.0.0` branch is, each of #28 and #29 is the feature which requires to increase MAJOR version. Therefore, I want to release both of them at the same time (If we do not so, MAJOR version will increase 2 versions in short term). Now, both #28 and #29 are resolved and it is ready to merge I think.

**Comment by mecab** [comment]
Thanks, I just misunderstood that you are going to all of the remaining issues. Yeah, #27 will not break the backward compat. Shipit :shipit:.

**Review by mecab — APPROVED** [review]
💨💨💨

**Pull request merged**
